server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    spring.jpa.database.platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

clientUsersApi:
  users:
#    name: "polls-api"
    url: "http://localhost:8081/users"
    # i didn't use port 8080 because if anyone wants to run any other project while that project running it will runs automatic on port 8080